-- NOTE: This file is auto generated by ./sql-generator

-- DownloadRepository.getForVariants
select
  "asset"."id",
  "asset"."ownerId",
  "asset"."type",
  "asset"."originalPath",
  "asset"."originalFileName",
  "asset"."checksum",
  "asset_exif"."exifImageWidth" as "width",
  "asset_exif"."exifImageHeight" as "height",
  "asset_video"."codecName" as "videoCodec",
  (
    select
      coalesce(json_agg(agg), '[]')
    from
      (
        select
          "asset_file"."type",
          "asset_file"."path",
          "asset_file"."isEdited",
          "asset_file"."updateId"
        from
          "asset_file"
        where
          "asset_file"."assetId" = "asset"."id"
      ) as agg
  ) as "files"
from
  "asset"
  left join "asset_exif" on "asset_exif"."assetId" = "asset"."id"
  left join "asset_video" on "asset_video"."assetId" = "asset"."id"
where
  "asset"."id" = any ($1::uuid[])
  and "asset"."deletedAt" is null

-- DownloadRepository.getExistingAssetIds
select
  "asset"."id"
from
  "asset"
where
  "asset"."id" = any ($1::uuid[])
